name: msktutil macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { cc-version: gcc }
          - { cc-version: clang }
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build msktutil ${{ matrix.cfg.cc-version }}
      shell: sh
      run: |
        case "${{ matrix.cfg.cc-version }}" in
          gcc)
            export CC=gcc
            export CXX=g++
            ;;
          clang)
            export CC=clang
            export CXX=clang++
            ;;
        esac
        ./autogen.sh
        ./configure && make
